### ISSUE TITLE
Can't use CPPCheckBear

### ISSUE THREAD

**Issue by stefanoco** [coala/docker-coala-base#10]
Trying to use CPPCheckBear on `pre` docker.
My gitlab-ci.yml contains:

``` yaml
  image: coala/base:pre
  script:
    - coala-ci
```

The resulting build shows:

``` bash
gitlab-ci-multi-runner 1.2.0
Using Docker executor with image coala/base:pre ...
Pulling docker image coala/base:pre ...
Running on runner-dc1af98e-project-278-concurrent-0 via stefanoco64pc...
Fetching changes...
HEAD is now at <skip>
From <skip>
Checking out <skip>
$ coala-ci
[WARNING][18:55:58] No bears were found matching 'CPPCheckBear'.
Executing section Default...
```

Please note that building the same container locally everything works well

**Comment by sils** [comment]
@fneu can you try reproducing this?

**Comment by fneu** [comment]
I can confirm and the reason is obvious I think.

Our dockerfile in the `pre` branch doesn't actually install the latest version of coala but the latest release. Yes it's the exact same file as on master. CPPCheckBear is not available in that version.

Running `pip install --no-cache-dir --pre --upgrade coala-bears` installed the latest coala and made CPPCheckBear available for me. I will add the `--pre` flag to our `pre` branch now and that should fix it.

**Comment by fneu** [comment]
fixed for me
