### ISSUE TITLE
Release coala 0.10 image

### ISSUE THREAD

**Issue by underyx** [coala/docker-coala-base#125]
It's been three weeks since the coala release 👯 

@chauffer tried bumping the version but MarkdownBear seemed to have some issues (which aren't happening with 0.9), it was trying to remove all content from markdown files. If I recall correct that happens when the wrong `remark` (`remark` instead of `remark-cli`) is installed. Can we investigate that?

**Comment by underyx** [comment]
This could be related, too https://github.com/coala/coala-bears/issues/1444

What do you think @jayvdb?

**Comment by underyx** [comment]
cc @sils as well

**Comment by fneu** [comment]
@jayvdb is there anything stopping this? Otherwise I'd try to make a release later today

**Comment by sils** [comment]
@fneu :point_up: [March 7, 2017 9:09 AM](https://gitter.im/coala/coala/maintainers?at=58be6ab5de5049082256b051)

**Comment by jayvdb** [comment]
The outstanding problem is 0.10 has checkstyle problems, with fixes merged but not yet released.
One possible solution is https://github.com/coala/docker-coala-base/issues/50 , which ensures the images has it so no extra fetch is needed/cant break.

**Comment by fneu** [comment]
so adding the `checkstyle.jar` to `/usr/local/share/coala-bears/CheckstyleBear/` would be enough for now to release 0.10?

@jayvdb is that and the release branch something you could take care of?

**Comment by jayvdb** [comment]
Yup, correct.

Not easy for me to do atm. On tablet only trying to fix laptop atm.
After that, if someone can push a branch 'release/0.10', it will voodoo be 0.10 because of https://github.com/coala/docker-coala-base/pull/123 .

**Comment by fneu** [comment]
@jayvdb like this? https://github.com/coala/docker-coala-base/pull/131

**Comment by underyx** [comment]
The problem I mentioned in the description is not fixed in the `0.10` image. MarkdownBear is still just deleting everything.

**Comment by fneu** [comment]
@underyx that sounds horrifying indeed. While there is a `0.10` docker tag atm, `latest` still points at `0.9` for now.

The thing is, inside the dockerfile we call `npm install` using the `package.json` provided by coala which includes `remark-cli` as well as `remark-lint`. These seem to get installed as to the output [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/208711380/log.txt). 

Unfortunately I cannot run the images atm because of memory limitations on my only device, I need to repartition something to give myself some more freedom but I cannot do that until the weekend.

@jayvdb can you investigate?

**Comment by fneu** [comment]
seems to be a coala/MarkdownBear related issue independent of docker

**Comment by underyx** [comment]
From [coala-bears 0.10.1 changelog](https://github.com/coala/coala-bears/releases/tag/0.10.1):

>Remark dependency has been pinned back to ~5.4 because version 6 changes
current behavior and breaks tests

From inside the `coala/base:0.10` image:

```
bash-4.4# remark --version
remark: 6.2.0, remark-cli: 2.1.0
```

So, I'm pretty sure as noted on gitter it's still just a question of uploading the image with the correct coala-bears version. Could someone do that?

**Comment by underyx** [comment]
(@jayvdb seems like the obvious user to tag here)

**Comment by jayvdb** [comment]
@underyx , the problem with MarkdownBear has been occurring since December. See https://github.com/coala/coala-bears/issues/1235

That commit message was a bit confusing, unless you look at the diff.
[remark-lint](https://www.npmjs.com/package/remark-lint) is now 7, so it needed to be pinned to 6.
[remark-cli](https://www.npmjs.com/package/remark-cli) is now 3, so it needed to be pinned to 2.

`latest` was still pointing at 0.9 ; I've now updated it to point to 0.10, and started builds for 0.9 and 0.10 and `latest`

**Comment by jayvdb** [comment]
This is blocked by https://github.com/coala/coala-bears/pull/1625

**Comment by jayvdb** [comment]
And there could also be a problem with cabal , for which there isnt an easy backport as `coala-bears.cabal` was created after the 0.10 release.

**Comment by jayvdb** [comment]
Problems all fixed.

Green build using this docker master with the bears branch `release/0.10` : https://travis-ci.org/jayvdb/docker-coala-base/builds/224080527

So, I've fast forward merged master into the branch `release/0.10`, and then will trigger a docker build.

The 0.10 image will already be smaller than prior images, but we can also revert https://github.com/coala/docker-coala-base/pull/134 on the 0.10 release branch, as that is only needed for 0.11 bears.  Started that now: https://github.com/coala/docker-coala-base/pull/163

**Comment by jayvdb** [comment]
Any objections to moving 'latest' to '0.10'?

**Comment by jayvdb** [comment]
I have updated 'latest' to 0.10, and it is building now. 1 hr until build completion to raise an objection.

**Comment by jayvdb** [comment]
latest is now 0.10
