### ISSUE TITLE
0.10 container serves coala version 0.12 development

### ISSUE THREAD

**Issue by sils** [coala/docker-coala-base#171]
```
$ docker run -t -i coala/base:0.10 coala --version
0.12.0.dev99999999999999
```

**Comment by jayvdb** [comment]
The problem is clicking trigger build on Docker Hub doesnt set [the arg `build`](https://github.com/coala/docker-coala-base/blob/master/Dockerfile#L4), and .. it cant according to https://github.com/docker/hub-feedback/issues/508 .  So those manually triggered builds use `branch=master`.

However, it seems like it is possible to set arg using hook for Docker Cloud.
I've set up a test case branch [hook-test](https://github.com/coala/docker-coala-base/tree/hook-test), but [that build](https://cloud.docker.com/swarm/coala/repository/registry-1.docker.io/coala/base/builds/f43836db-d5e7-4426-9cef-98db0f7bdef9) is taking forever to start (I probably used to many builds while trying a different solution that didnt work out.)

**Comment by jayvdb** [comment]
I've tested the 'trigger' button on Docker Cloud, and it also results in a build with `branch=master`, even when a "Build Environment Variables" is added for `branch={sourceref}`.

OTOH, a build hook works on Docker Hub, and presumably also works on Docker Cloud.

**Comment by jayvdb** [comment]
My 'evidence' that the build hook works is https://hub.docker.com/r/coala/base/builds/bgsuyaqjzxsmpblmnvjr8bz/ , where it is a manually triggered build that tries to checkout coala branch `hook-test`.
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...

Executing build hook...
Sending build context to Docker daemon 97.79 kB

Step 1/21 : FROM opensuse:tumbleweed
...
Cloning into 'coala'... 
warning: Could not find remote branch hook-test to clone.
fatal: Remote branch hook-test not found in upstream origin
```

**Comment by jayvdb** [comment]
This problem affected 0.10 and 0.11rc, and the fix has been backported to both, and images rebuilt for both.
